(add-to-list 'default-frame-alist '(font . "Droid Sans Mono:12" ))
(global-set-key (kbd "C-c C-t C-f C-f") 'toggle-frame-fullscreen)
(global-set-key (kbd "C-.") 'eshell)
(setq backup-directory-alist '(("[[:word:]]+" . "~/.emacs.d/backups")))
(provide 'misc-settings)
